name: Azure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  find-flag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          client-id: ec64da6b-23ce-4aca-b58c-b7f9401a6d1f
          tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
          subscription-id: 57965e50-018b-4f5e-9b9b-08accfa673bd

      - name: 'Download and Display the Flag'
        run: |
          az storage container list --account-name iamazurelab3dc5d4de3 --auth-mode login
          az storage blob list --account-name iamazurelab3dc5d4de3 --container-name flag --auth-mode key
          az storage blob download --account-name iamazurelab3dc5d4de3 --container-name flag --name flag.txt  --file "./flag.txt"
          
      
          echo "--- FLAG FOUND ---"
          cat flag.txt
          echo "------------------"
        # 上記の <YOUR_STORAGE_ACCOUNT_NAME> は、先ほど作成したストレージアカウント名に書き換えてください。
        # 例: ctfstorage12ab
